# Generated by Django 4.1.7 on 2023-02-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
